Source:
  position: 1
NewPage:
  position: 2
Preview:
  position: 3
Templates:
  position: 4
  label: [templates, button]
Cut:
  position: 5
Copy:
  position: 6
Paste:
  position: 7
PasteText:
  position: 8
  label: [pasteText, button]
PasteFromWord:
  position: 9
  label: [pastefromword, toolbar]
Print:
  position: 10
SpellChecker:
  position: 11
  label: [spellCheck, toolbar]
Scayt:
  position: 12
  label: [scayt, title]
Undo:
  position: 13
Redo:
  position: 14
Find:
  position: 15
  label: [findAndReplace, find]
Replace:
  position: 16
  label: [findAndReplace, replace]
SelectAll:
  position: 17
RemoveFormat:
  position: 18
Bold:
  position: 19
Italic:
  position: 20
Underline:
  position: 21
Strike:
  position: 22
Subscript:
  position: 23
Superscript:
  position: 24
NumberedList:
  position: 25
  label: numberedlist
BulletedList:
  position: 26
  label: bulletedlist
Outdent:
  position: 27
Indent:
  position: 28
Blockquote:
  position: 29
CreateDiv:
  position: 30
  label: [div, toolbar]
JustifyLeft:
  position: 31
  label: [justify, left]
JustifyCenter:
  position: 32
  label: [justify, center]
JustifyRight:
  position: 33
  label: [justify, right]
JustifyBlock:
  position: 34
  label: [justify, block]
BidiLtr:
  position: 35
  label: [bidi, ltr]
BidiRtl:
  position: 36
  label: [bidi, rtl]
Link:
  position: 37
  label: [link, toolbar]
Unlink:
  position: 38
Anchor:
  position: 39
  label: [anchor, toolbar]
Image:
  position: 40
  label: [image, title]
Table:
  position: 41
  label: [table, toolbar]
HorizontalRule:
  position: 42
  label: horizontalrule
Smiley:
  position: 43
  label: [smiley, toolbar]
SpecialChar:
  position: 44
  label: [specialChar, toolbar]
PageBreak:
  position: 45
  label: pagebreak
Styles:
  position: 46
  label: [stylesCombo, label]
Format:
  position: 47
  label: [format, label]
Font:
  position: 48
  label: [font, label]
FontSize:
  position: 49
  label: [fontSize, label]
TextColor:
  position: 50
  label: [colorButton, textColorTitle]
BGColor:
  position: 51
  label: [colorButton, bgColorTitle]
Maximize:
  position: 52
ShowBlocks:
  position: 53
About:
  position: 54
  label: [about, title]
